spring:
  application:
    name: currencycalculator
  datasource:
    url: jdbc:h2:mem:currencycalc
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /console
exchange:
  api:
    urlCurrent: https://www.lb.lt/webservices/FxRates/FxRates.asmx/getCurrentFxRates?tp=EU
    urlPeriod: https://www.lb.lt/webservices/FxRates/FxRates.asmx/getFxRatesForCurrency?tp=EU
  rate:
    fetch:
      cron: "0 0 6 * * ?"